import test from 'node:test';import assert from 'node:assert/strict';import {loadTs} from './load.mjs';
const M=await loadTs('mentorship.ts');
test('usta en az seviye 5, aralarında en az 2 seviye fark',()=>{const m=M.emptyMentorship();
  assert.ok(M.pairBlock(m,4,{nick:'a',level:1}));
  assert.equal(M.pairBlock(m,5,{nick:'a',level:3}),null);
  assert.ok(M.pairBlock(m,5,{nick:'a',level:4}));
  assert.ok(M.pairBlock(m,12,{nick:'a',level:6}));assert.equal(M.pairBlock(m,8,{nick:'a',level:5}),null);});
test('ustasız seviye 6 kilitlenir, ustalı 8 mezun olur',()=>{const a=M.emptyMentorship();M.onOwnLevel(a,5);assert.equal(a.lockedOut,false);M.onOwnLevel(a,6);assert.ok(a.lockedOut);assert.ok(M.apprenticeBlock(a,3));
  const b=M.emptyMentorship();b.mentor={nick:'u',level:10};const r=M.onOwnLevel(b,8);assert.ok(b.graduated);assert.equal(b.mentor,null);assert.equal(r.length,8);});
test('kabul, çıkarma ve usta ödülleri',()=>{const m=M.emptyMentorship();m.requests=[{nick:'c',level:3}];assert.equal(M.acceptRequest(m,9,'c'),null);assert.equal(m.apprentices.length,1);
  assert.equal(m.pending.length,1);assert.equal(M.onApprenticeLevel(m,'c',5).length,2);assert.equal(M.onApprenticeLevel(m,'c',5).length,0);assert.equal(M.onApprenticeLevel(m,'c',8).length,3);assert.equal(m.apprentices.length,0);assert.equal(m.graduates,1);
  m.apprentices=[{nick:'d',level:2,rewarded:[]}];M.removeApprentice(m,'d');assert.equal(m.apprentices.length,0);});
test('birlikteyken TP',()=>{assert.equal(M.apprenticeXp(100,true),150);assert.equal(M.apprenticeXp(100,false),100);});
test('ödüller talep edilene kadar bekler, bir kez alınır',()=>{const m=M.emptyMentorship();m.mentor={nick:'u',level:10};
  m.startLevel=5;assert.equal(M.onOwnLevel(m,5).length,1);assert.equal(M.onOwnLevel(m,5).length,0);assert.equal(m.pending.length,1);
  const r=M.claimReward(m,M.apprenticeKey(5));assert.equal(r.gold,M.MILESTONES[4].apprentice.gold);assert.equal(M.claimReward(m,M.apprenticeKey(5)),null);
  assert.ok(m.claimed.includes('app-5'));assert.equal(M.onOwnLevel(m,5).length,0);});
test('8 seviye sandık, katılınca o seviyenin sandığı açılır',()=>{assert.equal(M.MILESTONES.length,8);const m=M.emptyMentorship();
  assert.ok(M.joinMentor(m,{nick:'u',level:8},1));assert.equal(m.pending.length,1);M.onOwnLevel(m,4);assert.equal(m.pending.length,4);
  const x=M.emptyMentorship();x.lockedOut=true;assert.equal(M.joinMentor(x,{nick:'u',level:8},3),false);assert.equal(M.joinMentor(M.emptyMentorship(),{nick:'u',level:8},6),false);});
